// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJqG5N2R5js6mIcr9EA1NxZvOFCKJvhw',
    appId: '1:919508654566:web:d08962a177e62ba2d49e27',
    messagingSenderId: '919508654566',
    projectId: 'wizardmath-50907',
    authDomain: 'wizardmath-50907.firebaseapp.com',
    storageBucket: 'wizardmath-50907.firebasestorage.app',
    measurementId: 'G-LCZ457J4MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLwDyt4SU6kJ3w9XEGIqDXu9otuoshMrE',
    appId: '1:919508654566:android:8364b0036a30d7f7d49e27',
    messagingSenderId: '919508654566',
    projectId: 'wizardmath-50907',
    storageBucket: 'wizardmath-50907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWM4FmBPRsabVk_tGP6fLSeV_FYhmM6eo',
    appId: '1:919508654566:ios:ce9c71eabac75441d49e27',
    messagingSenderId: '919508654566',
    projectId: 'wizardmath-50907',
    storageBucket: 'wizardmath-50907.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWM4FmBPRsabVk_tGP6fLSeV_FYhmM6eo',
    appId: '1:919508654566:ios:ce9c71eabac75441d49e27',
    messagingSenderId: '919508654566',
    projectId: 'wizardmath-50907',
    storageBucket: 'wizardmath-50907.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIJqG5N2R5js6mIcr9EA1NxZvOFCKJvhw',
    appId: '1:919508654566:web:340ec2fc934ea502d49e27',
    messagingSenderId: '919508654566',
    projectId: 'wizardmath-50907',
    authDomain: 'wizardmath-50907.firebaseapp.com',
    storageBucket: 'wizardmath-50907.firebasestorage.app',
    measurementId: 'G-DLJHPML1XJ',
  );
}
